export const IPC = {
  // X preload -> main
  adapterRegister: 'adapter:register',
  adapterResult: 'adapter:result',
  historyLiked: 'history:liked',
  historyUnliked: 'history:unliked',
  focusChanged: 'focus:changed',
  // main -> X preload
  adapterCall: 'adapter:call',
  // sidebar <-> main
  agentSend: 'agent:send',
  agentInterrupt: 'agent:interrupt',
  agentNewThread: 'agent:newThread',
  agentReconnect: 'agent:reconnect',
  agentResolveApproval: 'agent:resolveApproval',
  agentResolveInput: 'agent:resolveInput',
  agentEvent: 'agent:event',
  agentListModels: 'agent:listModels',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  settingsChanged: 'settings:changed',
  settingsCodexBinary: 'settings:codexBinary',
  libraryList: 'library:list',
  libraryOpen: 'library:open',
  libraryChooseDir: 'library:chooseDir',
  historyClear: 'history:clear',
  historyStats: 'history:stats',
  focusUpdate: 'focus:update',
  sidebarSetCollapsed: 'sidebar:setCollapsed',
  sidebarCollapsed: 'sidebar:collapsed',
  linkOpen: 'link:open',
  sidebarFocusInput: 'sidebar:focusInput',
  conversationsList: 'conversations:list',
  conversationsOpen: 'conversations:open',
  tasksList: 'tasks:list',
  tasksUpdate: 'tasks:update',
  tasksDelete: 'tasks:delete',
  tasksRunNow: 'tasks:runNow',
} as const;
